### ISSUE TITLE
Call to undefined function.

### ISSUE THREAD

**Issue by rmcdermott** [bitsybay/bitsybay#10]
When attempting to upload a zip, I get this:

 PHP Fatal error:  Call to undefined function cl_scanfile() in /var/www/html/market/system/helper/validator/upload.php on line 48, referer: https://bitme.xyz/product/create

Any idea how I could resolve this?   Thanks.   I sent a small tip for the help with the sql.

**Comment by shaman** [comment]
You should install php-clamav extension:
https://github.com/bitsybay/bitsybay#requirements
