### ISSUE TITLE
Unable to rebuild database.

### ISSUE THREAD

**Issue by rmcdermott** [bitsybay/bitsybay#8]
I tried importing the database in phpmyadmin.   I also tried importing directly into mysql via command line.   What version of Mysql and apache was this writted for?   I am very interested in getting it up and running as I have a few changes I want to make and make it into a software marketplace.

My server is Debian 8.  What type of server / OS is the current bitsybay running on?

**Comment by shaman** [comment]
Hi, provide your import error details please.

MySQL 5.5
Apache 2.4
PHP 5.6

**Comment by rmcdermott** [comment]
When attempting an import via phpmyadmin, I get:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=InnoDBDEFAULT CHARSET=utf8' at line 9 

When attempting a import directly from mysql: 


ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=InnoDBDEFAULT CHARSET=utf8' at line 9

AND 

ERROR 1072 (42000): Key column 'language_id' doesn't exist in table.


I managed to fix the SQL syntax issue but still wind up with the 'language_id' doesn't exist in table no matter what I do.

**Comment by shaman** [comment]
#1064 and #1072 was fixed. Thank you!

https://github.com/bitsybay/bitsybay/commit/74e2a607bd0bcfff8c5470a934fc2279f32f7b25
https://github.com/bitsybay/bitsybay/commit/de4d03e2b0eb61b593ab13b385615bafd038490a
